name = "BINOD"
uuid = "a53c0f33-d76c-4691-9d44-64c4ed32e9f5"
authors = ["BINOD"]
version = "0.2.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
